# Generated by Django 4.1.1 on 2023-02-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_applications_bursary_student_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='bursary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursary.bursary'),
        ),
        migrations.AddField(
            model_name='applications',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bursary.student'),
        ),
    ]
