# Generated by Django 4.1.1 on 2023-02-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0003_applications_bursary_applications_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bursary',
            old_name='batch_number',
            new_name='batchNumber',
        ),
        migrations.AlterField(
            model_name='bursary',
            name='category',
            field=models.CharField(choices=[('County', 'County'), ('Constituency', 'Constituency'), ('Ward', 'Ward')], max_length=200, null=True),
        ),
    ]
