# Generated by Django 4.1.1 on 2023-02-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0004_rename_batch_number_bursary_batchnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='bursary.student'),
        ),
    ]
