# Generated by Django 4.1.1 on 2023-02-28 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bursary', '0011_student_gender_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Constituency',
            field=models.CharField(choices=[('Kibwezi West', 'Kibwezi West'), ('Kibwezi East', 'Kibwezi East')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='ward',
            field=models.CharField(choices=[('Sultan', 'Sultan'), ('Salama', 'Salama'), ('Konza', 'Konza'), ('Kibwezi', 'Kibwezi')], max_length=200, null=True),
        ),
    ]
