# Generated by Django 4.1.1 on 2023-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0013_applications_apply_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='apply_amount',
        ),
        migrations.AddField(
            model_name='applications',
            name='award',
            field=models.FloatField(choices=[('10,000', '10,000'), ('15,000', '15,000')], null=True),
        ),
    ]
