# Generated by Django 4.1.1 on 2023-03-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0014_remove_applications_apply_amount_applications_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='award',
        ),
        migrations.AddField(
            model_name='student',
            name='fees_structure',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
