# Generated by Django 4.1.1 on 2023-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0015_remove_applications_award_student_fees_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees_structure',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
