# Generated by Django 4.1.1 on 2023-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0016_alter_student_fees_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='apply_amount',
            field=models.FloatField(choices=[('8000', '8000'), ('10000', '10000')], null=True),
        ),
    ]
