# Generated by Django 4.1.1 on 2023-03-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0017_applications_apply_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='apply_amount',
            field=models.FloatField(choices=[('Eight Thousand', 'Eight Thousand'), ('Ten Thousand', 'Ten Thousand')], null=True),
        ),
    ]
