# Generated by Django 4.1.1 on 2023-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0018_alter_applications_apply_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='apply_amount',
        ),
        migrations.AddField(
            model_name='applications',
            name='applyAmount',
            field=models.FloatField(choices=[('Eight Thousand', 'Eight Thousand'), ('Ten Thousand', 'Ten Thousand')], null=True),
        ),
    ]
