# Generated by Django 4.1.1 on 2023-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0019_remove_applications_apply_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='applyAmount',
            field=models.CharField(choices=[('Eight Thousand', 'Eight Thousand'), ('Ten Thousand', 'Ten Thousand')], max_length=200, null=True),
        ),
    ]
